-- path: catalog-service/src/main/resources/db/migration/V3__more_subjects_and_courses.sql
-- purpose: them nhieu danh muc (AI, Toan, Van, Hoa, Tin hoc...) va khoa hoc mau.

INSERT INTO category (name, slug, description)
SELECT 'Toán', 'toan', 'Đại số, giải tích, xác suất thống kê' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'toan');
INSERT INTO category (name, slug, description)
SELECT 'Văn', 'van', 'Văn học, nghị luận, kỹ năng viết' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'van');
INSERT INTO category (name, slug, description)
SELECT 'Hóa', 'hoa', 'Hóa vô cơ, hữu cơ, thí nghiệm' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'hoa');
INSERT INTO category (name, slug, description)
SELECT 'Vật lý', 'vat-ly', 'Cơ, điện, quang học' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'vat-ly');
INSERT INTO category (name, slug, description)
SELECT 'Sinh học', 'sinh-hoc', 'Tế bào, di truyền, sinh thái' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'sinh-hoc');
INSERT INTO category (name, slug, description)
SELECT 'Tin học', 'tin-hoc', 'Tin học văn phòng, mạng, an toàn thông tin' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'tin-hoc');
INSERT INTO category (name, slug, description)
SELECT 'Ngoại ngữ', 'ngoai-ngu', 'Tiếng Anh, IELTS, giao tiếp' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'ngoai-ngu');
INSERT INTO category (name, slug, description)
SELECT 'Lịch sử', 'lich-su', 'Lịch sử Việt Nam và thế giới' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'lich-su');
INSERT INTO category (name, slug, description)
SELECT 'Địa lý', 'dia-ly', 'Địa lý tự nhiên và kinh tế' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'dia-ly');
INSERT INTO category (name, slug, description)
SELECT 'Kinh tế', 'kinh-te', 'Vi mô, vĩ mô, tài chính' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'kinh-te');
INSERT INTO category (name, slug, description)
SELECT 'Âm nhạc', 'am-nhac', 'Nhạc lý, piano, guitar, thanh nhạc' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'am-nhac');
INSERT INTO category (name, slug, description)
SELECT 'Nhiếp ảnh', 'nhiep-anh', 'Máy ảnh, ánh sáng, hậu kỳ' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'nhiep-anh');
INSERT INTO category (name, slug, description)
SELECT 'Video', 'video', 'Quay phim, dựng phim, YouTube' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'video');
INSERT INTO category (name, slug, description)
SELECT '3D & Animation', 'animation-3d', 'Blender, motion, nhân vật 3D' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'animation-3d');
INSERT INTO category (name, slug, description)
SELECT 'Kiến trúc', 'kien-truc', 'Thiết kế không gian, AutoCAD, SketchUp' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'kien-truc');
INSERT INTO category (name, slug, description)
SELECT 'Thời trang', 'thoi-trang', 'Thiết kế thời trang, styling' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'thoi-trang');
INSERT INTO category (name, slug, description)
SELECT 'Viết lách', 'viet-lach', 'Copywriting, storytelling, nội dung' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'viet-lach');
INSERT INTO category (name, slug, description)
SELECT 'Web & App', 'web-app', 'Thiết kế và phát triển web, ứng dụng' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'web-app');
INSERT INTO category (name, slug, description)
SELECT 'Ẩm thực', 'am-thuc', 'Nấu ăn, bánh, barista' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'am-thuc');
INSERT INTO category (name, slug, description)
SELECT 'Sức khỏe', 'suc-khoe', 'Yoga, dinh dưỡng, thể thao' WHERE NOT EXISTS (SELECT 1 FROM category WHERE slug = 'suc-khoe');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Trí tuệ nhân tạo cho người bắt đầu', 'tri-tue-nhan-tao-cho-nguoi-bat-dau', 'Hiểu machine learning qua ví dụ đời thường', 'Hiểu machine learning qua ví dụ đời thường. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 690000, 'BEGINNER', 'vi', 'AI,Machine Learning,Python', 'PUBLISHED', 1, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'ai' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tri-tue-nhan-tao-cho-nguoi-bat-dau');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Prompt Engineering làm chủ ChatGPT', 'prompt-engineering-lam-chu-chatgpt', 'Viết prompt ra kết quả đúng việc', 'Viết prompt ra kết quả đúng việc. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 390000, 'BEGINNER', 'vi', 'AI,Prompt,ChatGPT', 'PUBLISHED', 1, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'ai' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'prompt-engineering-lam-chu-chatgpt');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Computer Vision với Python', 'computer-vision-voi-python', 'Nhận diện ảnh và video từ camera', 'Nhận diện ảnh và video từ camera. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 890000, 'INTERMEDIATE', 'vi', 'AI,OpenCV,Computer Vision', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'ai' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'computer-vision-voi-python');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Toán cấp 3 ôn thi THPT', 'toan-cap-3-on-thi-thpt', 'Ôn tập hệ thống theo chuyên đề thi', 'Ôn tập hệ thống theo chuyên đề thi. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 299000, 'BEGINNER', 'vi', 'Toán,Đại số,Hình học', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'toan' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'toan-cap-3-on-thi-thpt');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Giải tích 1 cho sinh viên', 'giai-tich-1-cho-sinh-vien', 'Giới hạn, đạo hàm, tích phân có bài tập', 'Giới hạn, đạo hàm, tích phân có bài tập. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 420000, 'INTERMEDIATE', 'vi', 'Toán,Giải tích,Đạo hàm', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'toan' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'giai-tich-1-cho-sinh-vien');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Xác suất thống kê ứng dụng', 'xac-suat-thong-ke-ung-dung', 'Từ công thức đến phân tích dữ liệu', 'Từ công thức đến phân tích dữ liệu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 450000, 'INTERMEDIATE', 'vi', 'Toán,Xác suất,Thống kê', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'toan' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'xac-suat-thong-ke-ung-dung');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nghị luận văn học THPT', 'nghi-luan-van-hoc-thpt', 'Khung bài và dẫn chứng hay gặp', 'Khung bài và dẫn chứng hay gặp. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 249000, 'BEGINNER', 'vi', 'Văn,Nghị luận,Văn học', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'van' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'nghi-luan-van-hoc-thpt');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Văn học Việt Nam hiện đại', 'van-hoc-viet-nam-hien-dai', 'Đọc hiểu tác giả và tác phẩm tiêu biểu', 'Đọc hiểu tác giả và tác phẩm tiêu biểu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 320000, 'INTERMEDIATE', 'vi', 'Văn,Văn học,Phân tích', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'van' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'van-hoc-viet-nam-hien-dai');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Hóa hữu cơ từ gốc', 'hoa-huu-co-tu-goc', 'Cơ chế phản ứng và bài tập có lời giải', 'Cơ chế phản ứng và bài tập có lời giải. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 350000, 'BEGINNER', 'vi', 'Hóa,Hữu cơ,Phản ứng', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'hoa' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'hoa-huu-co-tu-goc');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Hóa vô cơ và bảng tuần hoàn', 'hoa-vo-co-va-bang-tuan-hoan', 'Tính chất nguyên tố, oxi hóa khử', 'Tính chất nguyên tố, oxi hóa khử. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 280000, 'BEGINNER', 'vi', 'Hóa,Vô cơ,Nguyên tố', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'hoa' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'hoa-vo-co-va-bang-tuan-hoan');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Vật lý cơ học THPT', 'vat-ly-co-hoc-thpt', 'Động học, lực, năng lượng', 'Động học, lực, năng lượng. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 310000, 'BEGINNER', 'vi', 'Vật lý,Cơ học', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'vat-ly' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'vat-ly-co-hoc-thpt');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Điện xoay chiều và mạch điện', 'dien-xoay-chieu-va-mach-dien', 'Định luật Kirchhoff đến mạch RLC', 'Định luật Kirchhoff đến mạch RLC. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 360000, 'INTERMEDIATE', 'vi', 'Vật lý,Điện', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'vat-ly' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'dien-xoay-chieu-va-mach-dien');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Sinh học tế bào và di truyền', 'sinh-hoc-te-bao-va-di-truyen', 'Từ tế bào đến quy luật Mendel', 'Từ tế bào đến quy luật Mendel. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 330000, 'BEGINNER', 'vi', 'Sinh học,Di truyền,ADN', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'sinh-hoc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'sinh-hoc-te-bao-va-di-truyen');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Sinh thái học và môi trường', 'sinh-thai-hoc-va-moi-truong', 'Hệ sinh thái, bảo tồn, biến đổi khí hậu', 'Hệ sinh thái, bảo tồn, biến đổi khí hậu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 270000, 'BEGINNER', 'vi', 'Sinh học,Sinh thái', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'sinh-hoc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'sinh-thai-hoc-va-moi-truong');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Tin học văn phòng Excel Word PowerPoint', 'tin-hoc-van-phong-excel-word-powerpoint', 'Làm việc văn phòng thành thạo', 'Làm việc văn phòng thành thạo. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 199000, 'BEGINNER', 'vi', 'Tin học,Excel,Word', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'tin-hoc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tin-hoc-van-phong-excel-word-powerpoint');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Mạng máy tính căn bản', 'mang-may-tinh-can-ban', 'IP, subnet, thiết bị mạng', 'IP, subnet, thiết bị mạng. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 420000, 'BEGINNER', 'vi', 'Tin học,Mạng,TCP/IP', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'tin-hoc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'mang-may-tinh-can-ban');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'An toàn thông tin cho người dùng', 'an-toan-thong-tin-cho-nguoi-dung', 'Mật khẩu, phishing, sao lưu dữ liệu', 'Mật khẩu, phishing, sao lưu dữ liệu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 390000, 'BEGINNER', 'vi', 'Tin học,Bảo mật,Cybersecurity', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'tin-hoc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'an-toan-thong-tin-cho-nguoi-dung');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Tiếng Anh giao tiếp 90 ngày', 'tieng-anh-giao-tiep-90-ngay', 'Phát âm và hội thoại hằng ngày', 'Phát âm và hội thoại hằng ngày. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 450000, 'BEGINNER', 'vi', 'Tiếng Anh,Giao tiếp', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'ngoai-ngu' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tieng-anh-giao-tiep-90-ngay');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Luyện thi IELTS 6.5+', 'luyen-thi-ielts-65', 'Chiến lược 4 kỹ năng và đề thi thử', 'Chiến lược 4 kỹ năng và đề thi thử. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 890000, 'INTERMEDIATE', 'vi', 'IELTS,Tiếng Anh', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'ngoai-ngu' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'luyen-thi-ielts-65');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Lịch sử Việt Nam thế kỷ 20', 'lich-su-viet-nam-the-ky-20', 'Các mốc lớn và tư liệu gốc', 'Các mốc lớn và tư liệu gốc. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 220000, 'BEGINNER', 'vi', 'Lịch sử,Việt Nam', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'lich-su' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'lich-su-viet-nam-the-ky-20');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Địa lý kinh tế Việt Nam', 'dia-ly-kinh-te-viet-nam', 'Vùng miền, tài nguyên, đô thị', 'Vùng miền, tài nguyên, đô thị. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 210000, 'BEGINNER', 'vi', 'Địa lý,Kinh tế', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'dia-ly' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'dia-ly-kinh-te-viet-nam');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Kinh tế vi mô nhập môn', 'kinh-te-vi-mo-nhap-mon', 'Cung cầu, chi phí, thị trường', 'Cung cầu, chi phí, thị trường. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 380000, 'BEGINNER', 'vi', 'Kinh tế,Vi mô', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kinh-te' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'kinh-te-vi-mo-nhap-mon');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Piano cho người mới bắt đầu', 'piano-cho-nguoi-moi-bat-dau', 'Hợp âm, tiết tấu, bài hát đầu tiên', 'Hợp âm, tiết tấu, bài hát đầu tiên. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 490000, 'BEGINNER', 'vi', 'Piano,Nhạc lý', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'am-nhac' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'piano-cho-nguoi-moi-bat-dau');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nhiếp ảnh điện thoại và máy ảnh', 'nhiep-anh-dien-thoai-va-may-anh', 'Bố cục, ánh sáng, chỉnh màu', 'Bố cục, ánh sáng, chỉnh màu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 390000, 'BEGINNER', 'vi', 'Nhiếp ảnh,Ánh sáng', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'nhiep-anh' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'nhiep-anh-dien-thoai-va-may-anh');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Dựng video với Premiere Pro', 'dung-video-voi-premiere-pro', 'Cắt ghép, subtitle, xuất bản', 'Cắt ghép, subtitle, xuất bản. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 590000, 'BEGINNER', 'vi', 'Video,Premiere,YouTube', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'video' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'dung-video-voi-premiere-pro');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Blender 3D cho người mới', 'blender-3d-cho-nguoi-moi', 'Model, material, render cảnh đầu tiên', 'Model, material, render cảnh đầu tiên. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 690000, 'BEGINNER', 'vi', 'Blender,3D,Animation', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'animation-3d' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'blender-3d-cho-nguoi-moi');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'SketchUp thiết kế nhà ở', 'sketchup-thiet-ke-nha-o', 'Mặt bằng, phối cảnh nội thất', 'Mặt bằng, phối cảnh nội thất. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 520000, 'BEGINNER', 'vi', 'Kiến trúc,SketchUp', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kien-truc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'sketchup-thiet-ke-nha-o');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Styling và phối đồ cá nhân', 'styling-va-phoi-do-ca-nhan', 'Màu sắc, form dáng, capsule wardrobe', 'Màu sắc, form dáng, capsule wardrobe. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 290000, 'BEGINNER', 'vi', 'Thời trang,Styling', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'thoi-trang' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'styling-va-phoi-do-ca-nhan');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Copywriting bán hàng', 'copywriting-ban-hang', 'Headline, landing page, email', 'Headline, landing page, email. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 350000, 'BEGINNER', 'vi', 'Viết,Copywriting', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'viet-lach' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'copywriting-ban-hang');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Thiết kế landing page Webflow', 'thiet-ke-landing-page-webflow', 'Từ wireframe đến trang chạy quảng cáo', 'Từ wireframe đến trang chạy quảng cáo. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 560000, 'BEGINNER', 'vi', 'Web,Webflow,UI', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'web-app' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'thiet-ke-landing-page-webflow');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nấu ăn gia đình 30 món', 'nau-an-gia-dinh-30-mon', 'Món Việt hằng ngày, mẹo gia vị', 'Món Việt hằng ngày, mẹo gia vị. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 250000, 'BEGINNER', 'vi', 'Ẩm thực,Nấu ăn', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'am-thuc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'nau-an-gia-dinh-30-mon');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Yoga tại nhà 15 phút', 'yoga-tai-nha-15-phut', 'Giãn cơ, thở, giảm đau lưng', 'Giãn cơ, thở, giảm đau lưng. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 180000, 'BEGINNER', 'vi', 'Yoga,Sức khỏe', 'PUBLISHED', 0, 0, 0, 0, NOW(6), NOW(6) FROM category c WHERE c.slug = 'suc-khoe' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'yoga-tai-nha-15-phut');
