spring.application.name=commerce-service
server.port=8085
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/commerce_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:nam123}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
jwt.secret=${JWT_SECRET:LearnHub-Shared-Secret-Key-2026-Doi-Trong-Moi-Truong-That}
internal.api-key=${INTERNAL_KEY:learnhub-internal-key-2026}
services.catalog-internal-url=${CATALOG_INTERNAL_URL:http://localhost:8082}
services.learning-internal-url=${LEARNING_INTERNAL_URL:http://localhost:8083}
services.identity-internal-url=${IDENTITY_INTERNAL_URL:http://localhost:8081}
commerce.platform-fee-percent=30
commerce.ai-extra-percent=5
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [trace=%X{traceId}] %logger{20} - %msg%n
