INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Bán hàng online cho cửa hàng nhỏ', 'ban-hang-online-cho-cua-hang-nho', 'Shopee, Facebook và chăm sóc khách', 'Shopee, Facebook và chăm sóc khách. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 320000, 'BEGINNER', 'vi', 'Kinh doanh,Bán hàng', 'PUBLISHED', 0, 4.70, 86, 1240, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kinh-doanh' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'ban-hang-online-cho-cua-hang-nho');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Quản trị nhóm và họp hiệu quả', 'quan-tri-nhom-va-hop-hieu-qua', 'Điều hành team 5 đến 20 người', 'Điều hành team 5 đến 20 người. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 410000, 'INTERMEDIATE', 'vi', 'Kinh doanh,Quản lý', 'PUBLISHED', 0, 4.80, 54, 890, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kinh-doanh' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'quan-tri-nhom-va-hop-hieu-qua');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Photoshop từ zero đến poster', 'photoshop-tu-zero-den-poster', 'Retouch, layer, poster sự kiện', 'Retouch, layer, poster sự kiện. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 480000, 'BEGINNER', 'vi', 'Thiết kế,Photoshop', 'PUBLISHED', 0, 4.60, 210, 3400, NOW(6), NOW(6) FROM category c WHERE c.slug = 'thiet-ke' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'photoshop-tu-zero-den-poster');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Thiết kế logo và nhận diện thương hiệu', 'thiet-ke-logo-va-nhan-dien-thuong-hieu', 'Từ brief đến bộ nhận diện hoàn chỉnh', 'Từ brief đến bộ nhận diện hoàn chỉnh. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 550000, 'INTERMEDIATE', 'vi', 'Thiết kế,Branding', 'PUBLISHED', 0, 4.90, 77, 1560, NOW(6), NOW(6) FROM category c WHERE c.slug = 'thiet-ke' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'thiet-ke-logo-va-nhan-dien-thuong-hieu');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'SEO nội dung lên top Google', 'seo-noi-dung-len-top-google', 'Keyword, on-page, đo lường Search Console', 'Keyword, on-page, đo lường Search Console. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 470000, 'BEGINNER', 'vi', 'Marketing,SEO', 'PUBLISHED', 0, 4.50, 133, 2100, NOW(6), NOW(6) FROM category c WHERE c.slug = 'marketing' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'seo-noi-dung-len-top-google');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Chạy ads Facebook và TikTok', 'chay-ads-facebook-va-tiktok', 'Chiến dịch, audience, tối ưu CPA', 'Chiến dịch, audience, tối ưu CPA. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 620000, 'INTERMEDIATE', 'vi', 'Marketing,Ads', 'PUBLISHED', 0, 4.70, 98, 1870, NOW(6), NOW(6) FROM category c WHERE c.slug = 'marketing' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'chay-ads-facebook-va-tiktok');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nói trước công chúng không run', 'noi-truoc-cong-chung-khong-run', 'Cấu trúc bài nói và kiểm soát hơi', 'Cấu trúc bài nói và kiểm soát hơi. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 240000, 'BEGINNER', 'vi', 'Kỹ năng mềm,Thuyết trình', 'PUBLISHED', 0, 4.80, 64, 980, NOW(6), NOW(6) FROM category c WHERE c.slug = 'phat-trien-ban-than' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'noi-truoc-cong-chung-khong-run');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Tư duy phản biện hàng ngày', 'tu-duy-phan-bien-hang-ngay', 'Đặt câu hỏi, tránh ngụy biện', 'Đặt câu hỏi, tránh ngụy biện. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 260000, 'BEGINNER', 'vi', 'Kỹ năng mềm,Tư duy', 'PUBLISHED', 0, 4.60, 41, 670, NOW(6), NOW(6) FROM category c WHERE c.slug = 'phat-trien-ban-than' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tu-duy-phan-bien-hang-ngay');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Luyện thi TOEIC 750+', 'luyen-thi-toeic-750', 'Chiến lược listening reading và đề thử', 'Chiến lược listening reading và đề thử. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 690000, 'INTERMEDIATE', 'vi', 'TOEIC,Chứng chỉ', 'PUBLISHED', 0, 4.70, 112, 2450, NOW(6), NOW(6) FROM category c WHERE c.slug = 'luyen-thi-chung-chi' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'luyen-thi-toeic-750');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Làm văn miêu tả và biểu cảm', 'lam-van-mieu-ta-va-bieu-cam', 'Hình ảnh, chi tiết, giọng văn', 'Hình ảnh, chi tiết, giọng văn. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 210000, 'BEGINNER', 'vi', 'Văn,Viết', 'PUBLISHED', 0, 4.80, 39, 540, NOW(6), NOW(6) FROM category c WHERE c.slug = 'van' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'lam-van-mieu-ta-va-bieu-cam');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Hóa học THPT ôn thi khối B', 'hoa-hoc-thpt-on-thi-khoi-b', 'Chuyên đề điện phân, pe,este', 'Chuyên đề điện phân, pe,este. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 340000, 'INTERMEDIATE', 'vi', 'Hóa,THPT', 'PUBLISHED', 0, 4.60, 58, 920, NOW(6), NOW(6) FROM category c WHERE c.slug = 'hoa' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'hoa-hoc-thpt-on-thi-khoi-b');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Vật lý quang học và sóng', 'vat-ly-quang-hoc-va-song', 'Giao thoa, khúc xạ, bài tập thi', 'Giao thoa, khúc xạ, bài tập thi. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 330000, 'INTERMEDIATE', 'vi', 'Vật lý,Quang học', 'PUBLISHED', 0, 4.50, 47, 710, NOW(6), NOW(6) FROM category c WHERE c.slug = 'vat-ly' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'vat-ly-quang-hoc-va-song');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Giải phẫu người cơ bản', 'giai-phau-nguoi-co-ban', 'Cơ, xương, tuần hoàn cho người mới', 'Cơ, xương, tuần hoàn cho người mới. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 390000, 'BEGINNER', 'vi', 'Sinh học,Giải phẫu', 'PUBLISHED', 0, 4.90, 29, 430, NOW(6), NOW(6) FROM category c WHERE c.slug = 'sinh-hoc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'giai-phau-nguoi-co-ban');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Tiếng Anh grammar cấp tốc', 'tieng-anh-grammar-cap-toc', '12 thì và cấu trúc hay dùng', '12 thì và cấu trúc hay dùng. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 280000, 'BEGINNER', 'vi', 'Tiếng Anh,Grammar', 'PUBLISHED', 0, 4.70, 155, 2890, NOW(6), NOW(6) FROM category c WHERE c.slug = 'ngoai-ngu' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tieng-anh-grammar-cap-toc');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Lịch sử thế giới cận đại', 'lich-su-the-gioi-can-dai', 'Cách mạng công nghiệp đến thế chiến', 'Cách mạng công nghiệp đến thế chiến. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 230000, 'BEGINNER', 'vi', 'Lịch sử,Thế giới', 'PUBLISHED', 0, 4.60, 22, 310, NOW(6), NOW(6) FROM category c WHERE c.slug = 'lich-su' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'lich-su-the-gioi-can-dai');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Đọc sử qua bản đồ và tư liệu', 'doc-su-qua-ban-do-va-tu-lieu', 'Phương pháp sử học cho học sinh', 'Phương pháp sử học cho học sinh. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 200000, 'BEGINNER', 'vi', 'Lịch sử,Phương pháp', 'PUBLISHED', 0, 4.80, 18, 260, NOW(6), NOW(6) FROM category c WHERE c.slug = 'lich-su' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'doc-su-qua-ban-do-va-tu-lieu');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Địa lý tự nhiên các châu lục', 'dia-ly-tu-nhien-cac-chau-luc', 'Khí hậu, địa hình, sông ngòi', 'Khí hậu, địa hình, sông ngòi. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 220000, 'BEGINNER', 'vi', 'Địa lý,Tự nhiên', 'PUBLISHED', 0, 4.50, 27, 380, NOW(6), NOW(6) FROM category c WHERE c.slug = 'dia-ly' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'dia-ly-tu-nhien-cac-chau-luc');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Bản đồ và GIS cho người mới', 'ban-do-va-gis-cho-nguoi-moi', 'Đọc bản đồ, tọa độ, lớp dữ liệu', 'Đọc bản đồ, tọa độ, lớp dữ liệu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 360000, 'BEGINNER', 'vi', 'Địa lý,GIS', 'PUBLISHED', 0, 4.70, 33, 510, NOW(6), NOW(6) FROM category c WHERE c.slug = 'dia-ly' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'ban-do-va-gis-cho-nguoi-moi');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Kinh tế vĩ mô dễ hiểu', 'kinh-te-vi-mo-de-hieu', 'GDP, lạm phát, lãi suất', 'GDP, lạm phát, lãi suất. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 400000, 'BEGINNER', 'vi', 'Kinh tế,Vĩ mô', 'PUBLISHED', 0, 4.60, 71, 1340, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kinh-te' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'kinh-te-vi-mo-de-hieu');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Tài chính cá nhân 101', 'tai-chinh-ca-nhan-101', 'Ngân sách, quỹ khẩn, đầu tư sơ cấp', 'Ngân sách, quỹ khẩn, đầu tư sơ cấp. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 290000, 'BEGINNER', 'vi', 'Kinh tế,Tài chính', 'PUBLISHED', 0, 4.90, 190, 4200, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kinh-te' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tai-chinh-ca-nhan-101');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Guitar đệm hát 30 ngày', 'guitar-dem-hat-30-ngay', 'Hợp âm cơ bản và 10 bài hát', 'Hợp âm cơ bản và 10 bài hát. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 360000, 'BEGINNER', 'vi', 'Guitar,Âm nhạc', 'PUBLISHED', 0, 4.80, 88, 1670, NOW(6), NOW(6) FROM category c WHERE c.slug = 'am-nhac' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'guitar-dem-hat-30-ngay');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Thanh nhạc hát đúng tông', 'thanh-nhac-hat-dung-tong', 'Hơi, cộng minh, luyện gam', 'Hơi, cộng minh, luyện gam. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 420000, 'BEGINNER', 'vi', 'Thanh nhạc,Âm nhạc', 'PUBLISHED', 0, 4.70, 46, 760, NOW(6), NOW(6) FROM category c WHERE c.slug = 'am-nhac' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'thanh-nhac-hat-dung-tong');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Chân dung studio với một đèn', 'chan-dung-studio-voi-mot-den', 'Ánh sáng, pose, hậu kỳ Lightroom', 'Ánh sáng, pose, hậu kỳ Lightroom. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 450000, 'INTERMEDIATE', 'vi', 'Nhiếp ảnh,Studio', 'PUBLISHED', 0, 4.80, 61, 990, NOW(6), NOW(6) FROM category c WHERE c.slug = 'nhiep-anh' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'chan-dung-studio-voi-mot-den');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nhiếp ảnh đường phố buổi tối', 'nhiep-anh-duong-pho-buoi-toi', 'ISO, chống rung, kể chuyện bằng ảnh', 'ISO, chống rung, kể chuyện bằng ảnh. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 370000, 'BEGINNER', 'vi', 'Nhiếp ảnh,Street', 'PUBLISHED', 0, 4.60, 35, 580, NOW(6), NOW(6) FROM category c WHERE c.slug = 'nhiep-anh' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'nhiep-anh-duong-pho-buoi-toi');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Quay Reels và Shorts chuyên nghiệp', 'quay-reels-va-shorts-chuyen-nghiep', 'Kịch bản 15 giây, máy, ánh sáng', 'Kịch bản 15 giây, máy, ánh sáng. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 410000, 'BEGINNER', 'vi', 'Video,Shorts', 'PUBLISHED', 0, 4.70, 102, 2310, NOW(6), NOW(6) FROM category c WHERE c.slug = 'video' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'quay-reels-va-shorts-chuyen-nghiep');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'DaVinci Resolve màu phim', 'davinci-resolve-mau-phim', 'Color wheel, LUT, xuất bản', 'Color wheel, LUT, xuất bản. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 640000, 'INTERMEDIATE', 'vi', 'Video,Color', 'PUBLISHED', 0, 4.90, 44, 820, NOW(6), NOW(6) FROM category c WHERE c.slug = 'video' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'davinci-resolve-mau-phim');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nhân vật 3D trong Blender', 'nhan-vat-3d-trong-blender', 'Sculpt, retopo, rig cơ bản', 'Sculpt, retopo, rig cơ bản. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 790000, 'INTERMEDIATE', 'vi', 'Blender,3D', 'PUBLISHED', 0, 4.80, 53, 940, NOW(6), NOW(6) FROM category c WHERE c.slug = 'animation-3d' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'nhan-vat-3d-trong-blender');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Motion graphics After Effects', 'motion-graphics-after-effects', 'Logo reveal, lower third, explainer', 'Logo reveal, lower third, explainer. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 680000, 'BEGINNER', 'vi', 'After Effects,Motion', 'PUBLISHED', 0, 4.70, 91, 1780, NOW(6), NOW(6) FROM category c WHERE c.slug = 'animation-3d' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'motion-graphics-after-effects');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'AutoCAD 2D bản vẽ nhà ở', 'autocad-2d-ban-ve-nha-o', 'Layer, dim, layout in ấn', 'Layer, dim, layout in ấn. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 540000, 'BEGINNER', 'vi', 'AutoCAD,Kiến trúc', 'PUBLISHED', 0, 4.60, 67, 1210, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kien-truc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'autocad-2d-ban-ve-nha-o');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Nội thất căn hộ 60m2', 'noi-that-can-ho-60m2', 'Công năng, ánh sáng, vật liệu', 'Công năng, ánh sáng, vật liệu. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 480000, 'BEGINNER', 'vi', 'Nội thất,Kiến trúc', 'PUBLISHED', 0, 4.80, 40, 650, NOW(6), NOW(6) FROM category c WHERE c.slug = 'kien-truc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'noi-that-can-ho-60m2');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'May vá cơ bản tại nhà', 'may-va-co-ban-tai-nha', 'Máy may, đường may, sửa quần áo', 'Máy may, đường may, sửa quần áo. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 310000, 'BEGINNER', 'vi', 'Thời trang,May', 'PUBLISHED', 0, 4.90, 73, 1320, NOW(6), NOW(6) FROM category c WHERE c.slug = 'thoi-trang' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'may-va-co-ban-tai-nha');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Thiết kế rập áo sơ mi', 'thiet-ke-rap-ao-so-mi', 'Số đo, rập, thử form', 'Số đo, rập, thử form. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 520000, 'INTERMEDIATE', 'vi', 'Thời trang,Rập', 'PUBLISHED', 0, 4.70, 28, 410, NOW(6), NOW(6) FROM category c WHERE c.slug = 'thoi-trang' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'thiet-ke-rap-ao-so-mi');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Viết blog thu hút độc giả', 'viet-blog-thu-hut-doc-gia', 'Cấu trúc bài, tiêu đề, giọng văn', 'Cấu trúc bài, tiêu đề, giọng văn. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 270000, 'BEGINNER', 'vi', 'Viết,Blog', 'PUBLISHED', 0, 4.60, 59, 1080, NOW(6), NOW(6) FROM category c WHERE c.slug = 'viet-lach' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'viet-blog-thu-hut-doc-gia');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Kể chuyện ngắn 1000 chữ', 'ke-chuyen-ngan-1000-chu', 'Xung đột, nhân vật, kết', 'Xung đột, nhân vật, kết. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 300000, 'BEGINNER', 'vi', 'Viết,Truyện', 'PUBLISHED', 0, 4.80, 36, 520, NOW(6), NOW(6) FROM category c WHERE c.slug = 'viet-lach' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'ke-chuyen-ngan-1000-chu');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'HTML CSS dựng trang công ty', 'html-css-dung-trang-cong-ty', 'Flexbox, responsive, form liên hệ', 'Flexbox, responsive, form liên hệ. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 390000, 'BEGINNER', 'vi', 'HTML,CSS,Web', 'PUBLISHED', 0, 4.70, 140, 3560, NOW(6), NOW(6) FROM category c WHERE c.slug = 'web-app' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'html-css-dung-trang-cong-ty');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'App điện thoại với Flutter', 'app-dien-thoai-voi-flutter', 'Widget, navigation, gọi API', 'Widget, navigation, gọi API. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 2, 720000, 'INTERMEDIATE', 'vi', 'Flutter,App', 'PUBLISHED', 0, 4.80, 84, 1490, NOW(6), NOW(6) FROM category c WHERE c.slug = 'web-app' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'app-dien-thoai-voi-flutter');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Làm bánh mì và bánh ngọt', 'lam-banh-mi-va-banh-ngot', 'Men, lò, công thức 12 món', 'Men, lò, công thức 12 món. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 280000, 'BEGINNER', 'vi', 'Ẩm thực,Bánh', 'PUBLISHED', 0, 4.90, 95, 1880, NOW(6), NOW(6) FROM category c WHERE c.slug = 'am-thuc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'lam-banh-mi-va-banh-ngot');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Pha chế cà phê tại nhà', 'pha-che-ca-phe-tai-nha', 'Pour over, espresso, sữa', 'Pour over, espresso, sữa. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 260000, 'BEGINNER', 'vi', 'Ẩm thực,Cà phê', 'PUBLISHED', 0, 4.80, 70, 1250, NOW(6), NOW(6) FROM category c WHERE c.slug = 'am-thuc' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'pha-che-ca-phe-tai-nha');

INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Tập gym cho người mới', 'tap-gym-cho-nguoi-moi', 'Lịch 3 buổi, kỹ thuật, dinh dưỡng', 'Lịch 3 buổi, kỹ thuật, dinh dưỡng. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 220000, 'BEGINNER', 'vi', 'Gym,Sức khỏe', 'PUBLISHED', 0, 4.70, 118, 2670, NOW(6), NOW(6) FROM category c WHERE c.slug = 'suc-khoe' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'tap-gym-cho-nguoi-moi');
INSERT INTO course (title, slug, subtitle, description, category_id, instructor_id, price, level, language, skills, status, ai_assist_enabled, rating_avg, rating_count, enrollment_count, created_at, published_at)
SELECT 'Ăn uống lành mạnh 4 tuần', 'an-uong-lanh-manh-4-tuan', 'Thực đơn, macro, đi chợ', 'Thực đơn, macro, đi chợ. Khóa học gồm video bài giảng, tài liệu, quiz và bài tập thực hành.', c.id, 3, 240000, 'BEGINNER', 'vi', 'Dinh dưỡng,Sức khỏe', 'PUBLISHED', 0, 4.60, 81, 1540, NOW(6), NOW(6) FROM category c WHERE c.slug = 'suc-khoe' AND NOT EXISTS (SELECT 1 FROM course WHERE slug = 'an-uong-lanh-manh-4-tuan');
